# Generated by Django 5.0.6 on 2024-06-17 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                (
                    "linkedin_url",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("is_demo_lead", models.BooleanField(default=False)),
                ("description", models.TextField(blank=True, null=True)),
                ("n_employees", models.FloatField(blank=True, null=True)),
                ("raw_json", models.JSONField(default=dict)),
                (
                    "company_name_linkedin",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("urn", models.IntegerField(blank=True, null=True)),
                ("campaign_id", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "lead",
            },
        ),
    ]
