# Generated by Django 5.0.6 on 2024-06-17 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                ("first_name", models.CharField(blank=True, max_length=255, null=True)),
                ("last_name", models.CharField(blank=True, max_length=255, null=True)),
                ("raw_json", models.JSONField(default=dict)),
                ("urn", models.IntegerField(blank=True, null=True)),
                ("lead_id", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "employee",
            },
        ),
    ]
